//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscapeFromDungeon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscapeFromDungeon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy01 {
            get {
                object obj = ResourceManager.GetObject("Enemy01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy02 {
            get {
                object obj = ResourceManager.GetObject("Enemy02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy03 {
            get {
                object obj = ResourceManager.GetObject("Enemy03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy04 {
            get {
                object obj = ResourceManager.GetObject("Enemy04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy05 {
            get {
                object obj = ResourceManager.GetObject("Enemy05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy06 {
            get {
                object obj = ResourceManager.GetObject("Enemy06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy07 {
            get {
                object obj = ResourceManager.GetObject("Enemy07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enemy08 {
            get {
                object obj = ResourceManager.GetObject("Enemy08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap EnemySimbol1 {
            get {
                object obj = ResourceManager.GetObject("EnemySimbol1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap EnemySimbol2 {
            get {
                object obj = ResourceManager.GetObject("EnemySimbol2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ID,EventType,message
        ///I0,ItemGet,ポーション
        ///I1,ItemGet,毒消し草
        ///I2,ItemGet,松明
        ///I3,ItemGet,バールのようなもの
        ///I4,ItemGet,炎の剣
        ///I5,ItemGet,氷の剣
        ///I6,ItemGet,雷の剣
        ///I7,ItemGet,聖なる剣
        ///I8,ItemGet,エクスカリバール
        ///E1,Encount,スライム
        ///E2,Encount,強そうなスライム
        ///E3,Encount,炎スライム
        ///E4,Encount,氷スライム
        ///E5,Encount,雷スライム
        ///E6,Encount,強そうな炎スライム
        ///E7,Encount,強そうな氷スライム
        ///E8,Encount,強そうな雷スライム
        ///E9,Encount,デーモン
        ///L0,Heal,HPが20回復した!
        ///L1,Heal,HPが50回復した!
        ///L2,Heal,HPが完全に回復した!
        ///L3,Heal,毒が治った!
        ///T0,Trap,罠だ！5のダメージを受けた!
        ///T1,Trap,痛い罠だ！20のダメージを受けた!
        ///T2,Trap,すごく痛い罠だ！40のダメージを受けた!        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前,説明
        ///ポーション,HPを30回復
        ///毒消し草,毒を治す
        ///松明,周囲を明るくする
        ///バールのようなもの,攻撃に打撃効果
        ///炎の剣,攻撃に炎の効果
        ///氷の剣,攻撃に氷の効果
        ///雷の剣,攻撃に雷の効果
        ///聖なる剣,攻撃に聖効果
        ///エクスカリバール,攻撃に打撃、炎、氷、雷、聖の効果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
        ///11,00,00,00,11,00,T2,11,00,00,00,00,00,00,00,00,00,00,00,12,E2,00,00,00,00,00,I0,11,00,00,00,00,00,00,00,XX,00,00,00,11
        ///11,00,11,00,11,00,11,11,00,11,11,XX,XX,11,00,11,00,11,00,11,11,00,00,11,00,11,11,11,00,11,11,XX,00,11,00,11,00,11,00,11
        ///11,00,11,00,00,00,00,00,00,00,00,11,11,11,00,11,T2,11,00,11,XX,12,11,11,00,00,00,11,00,XX,XX,XX,00,11,00,00,00,11,00,11
        ///11,00,11,11,11,11,12,11,11,1 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンスター名,HP,Atk,Weak
        ///スライム,20,1,None
        ///強そうなスライム,40,5,Thunder
        ///炎スライム,30,8,Ice
        ///氷スライム,30,9,Fire
        ///雷スライム,30,10,Heavy
        ///強そうな炎スライム,80,10,Ice
        ///強そうな氷スライム,80,10,Fire
        ///強そうな雷スライム,90,15,Heavy
        ///デーモン,200,20,Holy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap poisonTile {
            get {
                object obj = ResourceManager.GetObject("poisonTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
